version: '2'
services:
  api:
    build: app/api
    ports:
      - '3000:3000'
    volumes:
      - ./app/api:/home/app/api
      - /home/app/api/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
  nginx:
    image: nginx
    volumes:
      - ./app/site.conf:/etc/nginx/conf.d/default.conf
      - ./app/client/static:/www/data
    ports:
      - '8080:80'
    depends_on:
      - api
