version: '2'
services:
  api:
    build: app/api
    ports:
      - '3000:3000'
    volumes:
      - ./app/api:/home/app/api
      - /home/app/api/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
